url: jgoodall.me

gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

kramdown:
  input: GFM

future: false
paginate: 5
paginate_path: "/posts/page:num/"

# permalink: /posts/:year/:month/:day/:title

title: John R. Goodall
description: John Goodall is Research Scientist in the Cyber and Information Security Research group at Oak Ridge National Laboratory.
author: John Goodall
email: jgoodall@ornl.gov
phone: 865-446-0611

employer: Oak Ridge National Laboratory
employer_url: https://www.ornl.gov/
group: Cyber and Information Security Research group
group_url: http://www.csiir.ornl.gov/
team: Situation Awareness and Visual Analytics team

twitter: johnrgoodall
linkedin: johnrgoodall
github: jgoodall
speakerdeck: jgoodall
tumblr: johnrgoodall

cv_url: https://dl.dropbox.com/u/298645/goodall_cv.pdf
