url: jgoodall.me

author: John Goodall
email: jgoodall@ornl.gov
phone: 865-446-0611

employer: Oak Ridge National Laboratory
employer_url: https://www.ornl.gov/
group: Cyber and Information Security Research group
group_url: http://www.csiir.ornl.gov/
team: Situation Awareness and Visual Analytics team

twitter: johnrgoodall
linkedin: johnrgoodall
github: jgoodall
speakerdeck: jgoodall
tumblr: johnrgoodall

cv_url: https://dl.dropbox.com/u/298645/goodall_cv.pdf

future: false
# paginate: 10
permalink: /posts/:year/:month/:day/:title
